# Generated by Django 4.2.5 on 2024-07-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_address_product_city_product_num_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
